### PR TITLE
ConvertFrom-DSCObject: Fix some issues

### PR DESCRIPTION
**Pull request by ricmestre**
@NikCharlebois I'm currently handling a task in our solution that I was trying to solve it in a certain way, which is really not the best. Then I remembered you added *ConvertFrom-DSCObject* a few weeks ago and that's basically what I needed in the first place to solve my problem, I didn't use it up until now and I found some issues, mentioned below, and which this PR tries to fix all of them.

- Properties are not sorted
- Opening bracket after CIM instances is written in next line, on an M365DSC blueprint they appear right next to the CIM itself
- Strings that start with $ are enclosed in quotes, not a problem unless the input is something like $Object.Property
- Nested objects/CIM instances are of type OrderedDictionary, this type is not covered and so these objects do not appear
- Single CIM instances are written to the resulting string as an array even though we can extrapolate that it only contains a single object
- Arrays of CIM instances always have a carriage return at the end which results in an extra empty line before closing the array

### CODE REVIEW

**Review by ykuijs — APPROVED** [review]
LGTM

**Comment by ykuijs** [comment]
Nik is away for the next 1,5 weeks. I do not have permissions to merge PRs in this module (have to look at fixing that 😉), so we have to wait until he gets back unfortunately.

**Comment by ricmestre** [comment]
No problem, he also deserves some time off! I'll keep using a few workarounds in the meantime for my issues before this gets merged.

**Comment by ricmestre** [comment]
@NikCharlebois Welcome back! Any chance at looking at this and if everything seems right merge it into v2.0?

**Comment by NikCharlebois** [comment]
Can you merge the changes and I will merge the PR.

**Comment by ricmestre** [comment]
@nikcharlebois I've just merged your latest updates with my fixes.

**Pull request merged**
